### ISSUE TITLE
sometimes crashes during fallout

### ISSUE THREAD

**Issue by Scorched111** [Hamster-Systems/Hbm-s-Nuclear-Tech-GIT#29]
after a nuke when the fallout is converting the land the game sometimes crashes

---- Minecraft Crash Report ----
// Don't be sad, have a hug! <3

Time: 12/4/23 7:16 AM
Description: Exception ticking world

java.lang.IllegalArgumentException: Cannot get property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockPlanks$EnumType, values=[acacia, dark_oak]} as it does not exist in BlockStateContainer{block=hbm:waste_leaves, properties=[check_decay, decayable]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at net.minecraft.block.BlockNewLeaf.func_176234_a(BlockNewLeaf.java:37)
	at net.minecraft.block.BlockLeaves.getDrops(BlockLeaves.java:285)
	at net.minecraft.block.Block.getDrops(Block.java:1300)
	at net.minecraft.block.Block.func_180653_a(Block.java:571)
	at net.minecraft.block.BlockLeaves.func_180653_a(BlockLeaves.java:209)
	at net.minecraft.block.Block.func_176226_b(Block.java:564)
	at net.minecraft.block.BlockLeaves.func_176235_d(BlockLeaves.java:181)
	at net.minecraft.block.BlockLeaves.func_180650_b(BlockLeaves.java:173)
	at net.minecraft.block.Block.func_180645_a(Block.java:508)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:201)
	at net.minecraft.block.BlockNewLeaf.func_176234_a(BlockNewLeaf.java:37)
	at net.minecraft.block.BlockLeaves.getDrops(BlockLeaves.java:285)
	at net.minecraft.block.Block.getDrops(Block.java:1300)
	at net.minecraft.block.Block.func_180653_a(Block.java:571)
	at net.minecraft.block.BlockLeaves.func_180653_a(BlockLeaves.java:209)
	at net.minecraft.block.Block.func_176226_b(Block.java:564)
	at net.minecraft.block.BlockLeaves.func_176235_d(BlockLeaves.java:181)
	at net.minecraft.block.BlockLeaves.func_180650_b(BlockLeaves.java:173)
	at net.minecraft.block.Block.func_180645_a(Block.java:508)
	at net.minecraft.world.WorldServer.func_147456_g(WorldServer.java:476)
	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:225)

-- Affected level --
Details:
	Level name: New World
	All players: 1 total; [EntityPlayerMP['scorched1919'/1863, l='New World', x=-131.20, y=109.59, z=161.75]]
	Chunk stats: ServerChunkCache: 1000 Drop: 0
	Level seed: -179431140716076312
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-252,64,196), Chunk: (at 4,4,4 in -16,12; contains blocks -256,0,192 to -241,255,207), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 24527 game time, 24527 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 22725 (now: false), thunder time: 26201 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 204929496 bytes (195 MB) / 2480930816 bytes (2366 MB) up to 3847749632 bytes (3669 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4128m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 5 mods loaded, 5 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID        | Version                                             | Source                                                  | Signature                                |
	|:------ |:--------- |:--------------------------------------------------- |:------------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft | 1.12.2                                              | minecraft.jar                                           | None                                     |
	| LCHIJA | mcp       | 9.42                                                | minecraft.jar                                           | None                                     |
	| LCHIJA | FML       | 8.0.99.99                                           | forge-1.12.2-14.23.5.2860.jar                           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge     | 14.23.5.2860                                        | forge-1.12.2-14.23.5.2860.jar                           | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | hbm       | Hbms Nuclear Tech - Hamster Reloaded - 1.12.2-1.6.1 | Hbms Nuclear Tech - Hamster Reloaded - 1.12.2-1.6.1.jar | None                                     |

	Loaded coremods (and transformers): 
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['scorched1919'/1863, l='New World', x=-131.20, y=109.59, z=161.75]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'

**Comment by CharleyJQ** [comment]
Hi there! Thanks for the report. Can you confirm some of the below for me please.

Singleplayer or Multiplayer?
If Multiplayer; Hosted on a server or local hosted? 

Your Computer Specs:
RAM
CPU
GPU
How much ram is being given to Minecraft?

If your running on a Server what is it?
VPS/Dedicated Server, Etc
Specs of this server if possible.

Thanks.
Charley
Founder HS

**Comment by Scorched111** [comment]
single player

16gb

i5-11400

rtx 4060

6gb allocated

**Comment by CharleyJQ** [comment]
After looking into it, We have not been able to determin the cause for this, nor can we recreate it. They only difference we really have in SPECS is we're using 8GB of RAM instead of 6GB, However during fallout the geenration of terrain has to be semi rebuilt to change the blocks to either contaminated blocks or radioactive blocks. Crashes during these can be expected on low systems etc.

If you have more issues please recreate a issue report.

Thanks.
